version: '3.5'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  bot:
    image: test
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: 6638858172:AAEJ2N-9DTX8Pz31Iu4E-CX8BzWCFe2rPHk
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: postgres
      DBNAME: postgres
      SSLMODE: disable